### ISSUE TITLE
run debug error on mojave

### ISSUE THREAD

**Issue by mih30vip** [0xxd0/objc4#11]
dyld: Symbol not found: _objc_debug_taggedpointer_obfuscator
  Referenced from: /usr/lib/system/libxpc.dylib
  Expected in: /Users/xxxx/Library/Developer/Xcode/DerivedData/objc-ccgnoycdykfcdtfetssxtbpuvizg/Build/Products/Debug/libobjc.A.dylib
 in /usr/lib/system/libxpc.dylib

**Comment by mih30vip** [comment]
.

**Comment by showxu** [comment]
Update to latest objc4-781, macOS Catalina supported #12
