### ISSUE TITLE
Add macOS 11 Big Sur support

### ISSUE THREAD

**Issue by 0xxd0** [0xxd0/objc4#17]

**Comment by lengain** [comment]
同问

**Comment by 0xxd0** [comment]
> 同问

需要等 Big Sur objc4 在 opensource.apple.com 上 release 之后才能 support，目前为 objc4-787.1

**Comment by 0xxd0** [comment]
#20 Catalina 10.15.7 同样需要支持，等待 Apple Open Source 放出 tarball

**Comment by Colin225** [comment]
apple open source 已经放出了  objc4-818.2 ，感谢支持一下！
