### ISSUE TITLE
Mac OS 10.15.7 报这个错怎么解决

### ISSUE THREAD

**Issue by leixinggong** [0xxd0/objc4#20]
Static_assert failed due to requirement 'bucketsMask >= ((unsigned long long)140737454800896ULL)' "Bucket field doesn't have enough bits for arbitrary pointers."

**Comment by leixinggong** [comment]
![image](https://user-images.githubusercontent.com/17873915/102967832-c1ab3580-452d-11eb-9553-1a54dd002751.png)

**Comment by 0xxd0** [comment]
10.15.7 以及 Big Sur 的 objc runtime 有变化，目前 https://opensource.apple.com 上还没更新最新的 tarball，暂时无法使用

**Comment by 0xxd0** [comment]
10.15.7 tarball 未放出，建议使用 11.0.1 Big Sur 的 tarball 版本 objc4-818.2，目前 已支持，参考 README.md
